(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.cozydb = f()}})(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by CoffeeScript 1.8.0

}],2:[function(require,module,exports){
// Generated by CoffeeScript 1.8.0
}],3:[function(require,module,exports){
// Generated by CoffeeScript 1.8.0
(function() {
  var CozyBackedModel, Model, cozyDataAdapter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Model = require('./model');
 
  cozyDataAdapter = {
    find: function(callback) {
      var location = window.location;
      var xhr = new XMLHttpRequest();
      xhr.open("POST", "/ds-api/request/contact/all/", true);
      xhr.onload = function() {
        console.log("ONLOAD");
        console.log(xhr.response);
        console.log("ONLOAD");
        callback(null, xhr.response);
      }
      xhr.onerror = function(e) {
        err = "Request failed : #{e.target.status}";
        callback(err);
      }
      xhr.setRequestHeader("Content-Type", "application/json");
      xhr.send();
    },
    create: function(attributes, callback) {
      var path;
      path = "/ds-api/data/";
      console.log(attributes);
      var location = window.location;
      var xhr = new XMLHttpRequest();
      console.log(xhr);
      xhr.open("POST", path, true);
      xhr.onload = function() {
        callback(null, xhr.response);
      }
      xhr.onerror = function(e) {
        err = "Request failed : #{e.target.status}";
        callback(err);
      }
      xhr.setRequestHeader("Content-Type", "application/json");
      xhr.setRequestHeader("Authorization", "Basic " + btoa("frontpermission:" + "password"));
      xhr.send(JSON.stringify(attributes));
    }
  };

  module.exports = CozyBackedModel = (function(_super) {
    __extends(CozyBackedModel, _super);

    function CozyBackedModel() {
      return CozyBackedModel.__super__.constructor.apply(this, arguments);
    }

    CozyBackedModel.adapter = cozyDataAdapter;

    CozyBackedModel.cast = function() {
      console.log('CozyBackedModel');
      console.log(this.schema);
      if (!this.__addedToSchema) {
        this.__addedToSchema = true;
        this.schema._id = String;
        this.schema._attachments = Object;
        this.schema._rev = String;
        this.schema.id = String;
        this.schema.docType = String;
        this.schema.binaries = Object;
      }
      console.log('CozyBackedModel.__super__.constructor.cast.apply');
      console.log(this.schema);
      console.log(arguments);
      console.log(arguments[0]);
      return CozyBackedModel.__super__.constructor.cast.apply(this, arguments);
    };

    return CozyBackedModel;

  })(Model);

}).call(this);

},{"./model":5,"./utils/client":7,"./utils/later_stream":9,"form-data":12,"util":164}],4:[function(require,module,exports){
(function (process){
// Generated by CoffeeScript 1.8.0
(function() {
  var CozyModel, Model,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };


  console.log('************************************');

  module.exports.Model = Model = require('./model');

  module.exports.CozyModel = CozyModel = require('./cozymodel');

  module.exports.getModel = function(name, schema) {
    console.log('GET MODEL');
    var ClassFromGetModel, klass;
    klass = ClassFromGetModel = (function(_super) {
      console.log('************************');
      __extends(ClassFromGetModel, _super);

      function ClassFromGetModel() {
        console.log('ClassFromGetModel');
        return ClassFromGetModel.__super__.constructor.apply(this, arguments);
      }

      ClassFromGetModel.schema = schema;

      return ClassFromGetModel;

    })(CozyModel);
    klass.displayName = klass.name = name;
    console.log('klass.displayName');

    klass.toString = function() {
      return "" + name + "Constructor";
    };
    klass.docType = name;
    return klass;
  };

}).call(this);

}).call(this,require('_process'))
}],5:[function(require,module,exports){
(function (process){
// Generated by CoffeeScript 1.8.0
(function() {
  var Model,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __hasProp = {}.hasOwnProperty;


  Model = (function() {
    Model.getDocType = function() {
      var _ref;
      return ((_ref = this.docType) != null ? _ref.toLowerCase() : void 0) || this.name.toLowerCase();
    };

    Model.create = function(data, callback) {
      data.docType = this.getDocType();
      data = this.cast(data);
      return this.adapter.create(data, (function(_this) {
        return function(err, attributes) {
          var k, v;
          if (err) {
            return callback(err);
          }
          return callback(null, new _this(data));
        };
      })(this));
    };

    Model.cast = function(attributes, target) {
      console.log('Model.cast');
      if (target == null) {
        target = {};
      }
      console.log('_________________________CAST__________________');
      return castObject(attributes, this.schema, target, this.name);
    };

    return Model;

  })();

  module.exports = Model;
  console.log('_____________________CAST OBJECT_________________________');
  castObject = require('./utils/type_checking').castObject;
  console.log('_________________________________________________________');
}).call(this);
module.exports = extend

var hasOwnProperty = Object.prototype.hasOwnProperty;

function extend() {
    var target = {}

    for (var i = 0; i < arguments.length; i++) {
        var source = arguments[i]

        for (var key in source) {
            if (hasOwnProperty.call(source, key)) {
                target[key] = source[key]
            }
        }
    }

    return target
}

},{},{},[4](4)
)}]};